name: tennisiq_app
description: TennisIQ Flutter Application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_riverpod: ^2.4.3
  
  # Navigation
  go_router: ^12.1.1
  
  # Networking
  dio: ^5.3.3
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # UI
  fl_chart: ^0.65.0
  
  # Hardware / Media
  permission_handler: ^11.0.1
  flutter_blue_plus: ^1.15.10
  camera: ^0.10.5+5
  video_player: ^2.8.1
  audioplayers: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
