# Generated by Django 4.2 on 2026-04-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_acceleration', models.FloatField(default=0.0)),
                ('angular_velocity', models.FloatField(default=0.0)),
                ('swing_intensity', models.FloatField(default=0.0)),
                ('fatigue_score', models.FloatField(default=0.0)),
                ('hr_avg', models.FloatField(default=0.0)),
                ('hr_max', models.FloatField(default=0.0)),
                ('workout_load', models.FloatField(default=0.0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_metrics', to='sessions_log.matchsession')),
            ],
        ),
        migrations.CreateModel(
            name='VideoMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_distance_m', models.FloatField(default=0.0)),
                ('court_coverage_pct', models.FloatField(default=0.0)),
                ('avg_reaction_time_ms', models.FloatField(default=0.0)),
                ('shot_accuracy_pct', models.FloatField(default=0.0)),
                ('unforced_errors', models.IntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_metrics', to='sessions_log.matchsession')),
            ],
        ),
        migrations.CreateModel(
            name='FusionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing_score', models.FloatField(default=0.0)),
                ('consistency_score', models.FloatField(default=0.0)),
                ('stroke_quality_score', models.FloatField(default=0.0)),
                ('match_intensity', models.FloatField(default=0.0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fusion_metrics', to='sessions_log.matchsession')),
            ],
        ),
    ]
