# Generated by Django 4.2 on 2026-04-21 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_log', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometrics',
            name='homography_matrix',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videometrics',
            name='avg_reaction_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videometrics',
            name='court_coverage_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videometrics',
            name='movement_distance_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videometrics',
            name='shot_accuracy_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videometrics',
            name='unforced_errors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_job', to='sessions_log.matchsession')),
            ],
        ),
    ]
