# Generated by Django 4.2 on 2026-04-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_videometrics_homography_matrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometrics',
            name='dominant_court_zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
