# Generated by Django 4.2 on 2026-04-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_videometrics_dominant_court_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometrics',
            name='max_ball_speed_kmh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
