# Generated by Django 4.2 on 2026-04-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_videometrics_max_ball_speed_kmh'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometrics',
            name='avg_rally_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videometrics',
            name='max_rally_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videometrics',
            name='max_serve_speed_kmh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videometrics',
            name='movement_heatmap',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchmetrics',
            name='fatigue_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
