# Generated by Django 4.2 on 2026-04-20 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('mode', models.CharField(choices=[('video_only', 'Video Only'), ('watch_only', 'Watch Only'), ('fusion', 'Fusion')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrokeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_ms', models.BigIntegerField()),
                ('stroke_type', models.CharField(choices=[('forehand', 'Forehand'), ('backhand', 'Backhand'), ('serve', 'Serve'), ('volley', 'Volley'), ('smash', 'Smash'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('source', models.CharField(choices=[('video', 'Video'), ('watch', 'Watch'), ('fusion', 'Fusion')], max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stroke_events', to='sessions_log.matchsession')),
            ],
        ),
        migrations.CreateModel(
            name='RallyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ms', models.BigIntegerField()),
                ('end_ms', models.BigIntegerField()),
                ('rally_length', models.IntegerField(default=0)),
                ('winner', models.CharField(choices=[('player', 'Player'), ('opponent', 'Opponent'), ('net_error', 'Net Error'), ('out_error', 'Out Error'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rally_events', to='sessions_log.matchsession')),
            ],
        ),
    ]
